spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: mvsc_user
          uri: http://localhost:8090
          predicates:
            - Path=/auth/**
